#!/bin/bash

if [ $# -lt 5 ];then
	echo0 1 $0" in.bed2 in.feature.sizes out.prefix factor CPU picluster|transposon|gene"
	exit 1
fi
BED=${1}
SIZES=${2}
SAMP=${3}
FACTOR=$4
FACTOR_PP=`awk -v factor=$FACTOR 'BEGIN{print factor*factor}'`
CPU=$5

#echo $CPU $FACTOR ${SAMP} ${BED} ${SIZES}

PATH_BED2=${SAMP}_temp_bed2 && mkdir -p ${PATH_BED2}
PATH_LENDIS=${SAMP}_temp_lendis && mkdir -p ${PATH_LENDIS}
PATH_PP=${SAMP}_temp_pp && mkdir -p ${PATH_PP}
PATH_SIGNAL=${SAMP}_temp_signal && mkdir -p ${PATH_SIGNAL}
PARA_FILE1=${SAMP}_temp_para1
PARA_FILE2=${SAMP}_temp_para2
PARA_FILE3=${SAMP}_temp_para3
PARA_FILE4=${SAMP}_temp_para4
# seperate bed2 files
echo0 1 "........seperate bed2 file for each element"
seperate_bed2.py $BED $SIZES ${PATH_BED2}

# calculate informations of each element
for i in ${PATH_BED2}/*
do
	bn=`basename $i`
	n=${bn%.bed2}
	echo -e "bed2_lendis $i ${FACTOR} > ${PATH_LENDIS}/${n}.lendis" >> ${PARA_FILE1}
	echo -e "bed2_pingpong -a $i -b $i | awk -v factor=${FACTOR_PP} 'BEGIN{FS=OFS=\"\\\t\"} {print \$BED,\$2/factor}' > ${PATH_PP}/${n}.pp" >> ${PARA_FILE2}
	echo -e "awk -v factor=$FACTOR 'BEGIN{FS=OFS=\"\\\t\"} {if(\$6==\"+\" && \$5==1){sum1+=\$4/\$5}else if(\$6==\"-\" && \$5==1){sum2+=\$4/\$5};if(\$6==\"+\"){sum3+=\$4/\$5}else{sum4+=\$4/\$5}} END{print sum1/factor,sum2/factor,sum3/factor,sum4/factor}' $i > ${PATH_SIGNAL}/${n}.rpm" >> ${PARA_FILE3}
	echo -e "awk 'BEGIN{FS=OFS=\"\\\t\"} {if(\$6==\"+\" && \$5==1){sum1++}else if(\$6==\"-\" && \$5==1){sum2++}; if(\$6==\"+\"){sum3+=1/\$5}else{sum4+=1/\$5}} END{print sum1/1,sum2/1,sum3/1,sum4/1}' $i > ${PATH_SIGNAL}/${n}.species" >> ${PARA_FILE4}
done
echo0 1 "........calculate lendis"
ParaFly -c ${PARA_FILE1} -CPU ${CPU} > /dev/null && rm ${PARA_FILE1}
echo0 1 "........calculate ping-pong"
ParaFly -c ${PARA_FILE2} -CPU ${CPU} > /dev/null && rm ${PARA_FILE2}
echo0 1 "........calculate normalized reads"
ParaFly -c ${PARA_FILE3} -CPU ${CPU} > /dev/null && rm ${PARA_FILE3}
echo0 1 "........calculate species"
ParaFly -c ${PARA_FILE4} -CPU ${CPU} > /dev/null && rm ${PARA_FILE4}

# write matrix
echo0 1 "........seperate reads/species and all/uniqMappers for lendis"
PARA_FILE5=${SAMP}_temp_para5
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 2 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.uniq.reads.sense;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 3 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.uniq.reads.anti;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 4 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.uniq.species.sense;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 5 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.uniq.species.anti;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 6 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.all.reads.sense;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 7 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.all.reads.anti;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 8 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.all.species.sense;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 9 ${PATH_LENDIS}/\${n}.lendis | awk 'NR!=1' > ${PATH_LENDIS}/\${n}.all.species.anti;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};echo -en \"\\\t\${n}\" >> ${SAMP}_header1;done" > ${SAMP}_temp_bash1
echo -e "bash ${SAMP}_temp_bash1" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};cut -f 2 ${PATH_PP}/\${n}.pp > ${PATH_PP}/\${n}.ppc;done" >> ${PARA_FILE5}
echo -e "for i in ${PATH_BED2}/*;do bn=\`basename \$i\`;n=\${bn%.bed2};rd=\"\`cat ${PATH_SIGNAL}/\${n}.rpm\`\";sp=\"\`cat ${PATH_SIGNAL}/\${n}.species\`\";echo -e \"\${n}\\\t\${rd}\\\t\${sp}\" >> ${SAMP}_body4;done" > ${SAMP}_temp_bash2
echo -e "bash ${SAMP}_temp_bash2" >> ${PARA_FILE5}
ParaFly -c ${PARA_FILE5} -CPU ${CPU} > /dev/null && rm ${PARA_FILE5}
rm ${SAMP}_temp_bash*

echo0 1 "........merge all the informations to matrices"
PARA_FILE6=${SAMP}_temp_para6
echo -e "\tuniq_sense_reads\tuniq_antisense_reads\tall_sense_reads\tall_antisense_reads\tuniq_sense_species\tuniq_antisense_species\tall_sense_species\tall_antisense_species" > ${SAMP}_header2
echo -e "" >> ${SAMP}_header1
touch ${SAMP}_body1
echo -e "for i in ${PATH_LENDIS}/*uniq.reads.sense;do paste ${SAMP}_body1 \$i > ${SAMP}_t1 && mv ${SAMP}_t1 ${SAMP}_body1;done;cut -f 2- ${SAMP}_body1 > ${SAMP}_t1 && mv ${SAMP}_t1 ${SAMP}_body1" >> ${PARA_FILE6}
touch ${SAMP}_body2
echo -e "for i in ${PATH_LENDIS}/*uniq.reads.anti;do paste ${SAMP}_body2 \$i > ${SAMP}_t2 && mv ${SAMP}_t2 ${SAMP}_body2;done;cut -f 2- ${SAMP}_body2 > ${SAMP}_t2 && mv ${SAMP}_t2 ${SAMP}_body2" >> ${PARA_FILE6}
touch ${SAMP}_body3
echo -e "for i in ${PATH_PP}/*.ppc;do paste ${SAMP}_body3 \$i > ${SAMP}_t3 && mv ${SAMP}_t3 ${SAMP}_body3;done" >> ${PARA_FILE6}

touch ${SAMP}_body5
echo -e "for i in ${PATH_LENDIS}/*uniq.species.sense;do paste ${SAMP}_body5 \$i > ${SAMP}_t5 && mv ${SAMP}_t5 ${SAMP}_body5;done;cut -f 2- ${SAMP}_body5 > ${SAMP}_t5 && mv ${SAMP}_t5 ${SAMP}_body5" >> ${PARA_FILE6}
touch ${SAMP}_body6
echo -e "for i in ${PATH_LENDIS}/*uniq.species.anti;do paste ${SAMP}_body6 \$i > ${SAMP}_t6 && mv ${SAMP}_t6 ${SAMP}_body6;done;cut -f 2- ${SAMP}_body6 > ${SAMP}_t6 && mv ${SAMP}_t6 ${SAMP}_body6" >> ${PARA_FILE6}
touch ${SAMP}_body7
echo -e "for i in ${PATH_LENDIS}/*all.reads.sense;do paste ${SAMP}_body7 \$i > ${SAMP}_t7 && mv ${SAMP}_t7 ${SAMP}_body7;done;cut -f 2- ${SAMP}_body7 > ${SAMP}_t7 && mv ${SAMP}_t7 ${SAMP}_body7" >> ${PARA_FILE6}
touch ${SAMP}_body8
echo -e "for i in ${PATH_LENDIS}/*all.reads.anti;do paste ${SAMP}_body8 \$i > ${SAMP}_t8 && mv ${SAMP}_t8 ${SAMP}_body8;done;cut -f 2- ${SAMP}_body8 > ${SAMP}_t8 && mv ${SAMP}_t8 ${SAMP}_body8" >> ${PARA_FILE6}
touch ${SAMP}_body9
echo -e "for i in ${PATH_LENDIS}/*all.species.sense;do paste ${SAMP}_body9 \$i > ${SAMP}_t9 && mv ${SAMP}_t9 ${SAMP}_body9;done;cut -f 2- ${SAMP}_body9 > ${SAMP}_t9 && mv ${SAMP}_t9 ${SAMP}_body9" >> ${PARA_FILE6}
touch ${SAMP}_body10
echo -e "for i in ${PATH_LENDIS}/*all.species.anti;do paste ${SAMP}_body10 \$i > ${SAMP}_t10 && mv ${SAMP}_t10 ${SAMP}_body10;done;cut -f 2- ${SAMP}_body10 > ${SAMP}_t10 && mv ${SAMP}_t10 ${SAMP}_body10" >> ${PARA_FILE6}
ParaFly -c ${PARA_FILE6} -CPU ${CPU} > /dev/null && rm ${PARA_FILE6}

cut -f 2- ${SAMP}_body3 > ${SAMP}_t && mv ${SAMP}_t ${SAMP}_body3
cat ${SAMP}_header1 ${SAMP}_body1 > ${SAMP}.$6.uniq.reads.sense.lendis
cat ${SAMP}_header1 ${SAMP}_body2 > ${SAMP}.$6.uniq.reads.antisense.lendis
cat ${SAMP}_header1 ${SAMP}_body3 > ${SAMP}.$6.pp
cat ${SAMP}_header2 ${SAMP}_body4 > ${SAMP}.$6.summary
cat ${SAMP}_header1 ${SAMP}_body5 > ${SAMP}.$6.uniq.species.sense.lendis
cat ${SAMP}_header1 ${SAMP}_body6 > ${SAMP}.$6.uniq.species.antisense.lendis
cat ${SAMP}_header1 ${SAMP}_body7 > ${SAMP}.$6.all.reads.sense.lendis
cat ${SAMP}_header1 ${SAMP}_body8 > ${SAMP}.$6.all.reads.antisense.lendis
cat ${SAMP}_header1 ${SAMP}_body9 > ${SAMP}.$6.all.species.sense.lendis
cat ${SAMP}_header1 ${SAMP}_body10 > ${SAMP}.$6.all.species.antisense.lendis
rm ${SAMP}_header* ${SAMP}_body*
rm -rf ${SAMP}_temp*
